Repository duckie-team/quack-quack-android, pull requests merged in 2022-09, with the labels that each got.

#76 TrailingComma 규칙 구현
  lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/ComposeIssueRegistry.kt
  lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/TrailingCommaDetector.kt
  lint-compose/src/test/kotlin/team/duckie/quackquack/lint/compose/TrailingCommaTest.kt
Labels: lint, deploy, dokka, test

#82 KDocFields 린트 규칙 구현
  detekt-config.yml
  lint-core/src/main/kotlin/team/duckie/quackquack/lint/core/CoreIssueRegistry.kt
  lint-core/src/main/kotlin/team/duckie/quackquack/lint/core/KDocFieldsDetector.kt
  lint-core/src/test/kotlin/team/duckie/quackquack/lint/core/KDocFieldsTest.kt
Labels: lint, deploy, dokka, test

#85 Floating Action Button
  lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/NewLineArgumentDetector.kt
  lint-compose/src/test/kotlin/team/duckie/quackquack/lint/compose/NewLineArgumentTest.kt
  playground/src/main/AndroidManifest.xml
  playground/src/main/kotlin/team/duckie/quackquack/playground/MainActivity.kt
  playground/src/main/kotlin/team/duckie/quackquack/playground/base/common.kt
  playground/src/main/kotlin/team/duckie/quackquack/playground/realworld/FabPlayground.kt
  ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
  ui-components/src/main/kotlin/team/duckie/quackquack/ui/icon/QuackIcon.kt
  ui-components/src/main/res/drawable/ic_dm_new_20_white.xml
  ui-components/src/main/res/drawable/ic_drawer_buy_24.xml
  ui-components/src/main/res/drawable/ic_write_feed_24.xml
  ui-components/src/test/kotlin/team/duckie/quackquack/ui/QuackFab.kt
Labels: UI, deploy, dokka, test, release

#91 KDocFields 린트 규칙 구현 (2차)
  common-lint/src/main/kotlin/team/duckie/quackquack/common/lint/KDocChecker.kt
  detekt-config.yml
  lint-core/src/main/kotlin/team/duckie/quackquack/lint/core/CoreIssueRegistry.kt
  lint-core/src/main/kotlin/team/duckie/quackquack/lint/core/KDocFieldsDetector.kt
  lint-core/src/test/kotlin/team/duckie/quackquack/lint/core/KDocFieldsTest.kt
Labels: lint, deploy, dokka, test

#90 QuackTextField 구현 재시도
  playground/src/main/kotlin/team/duckie/quackquack/playground/MainActivity.kt
  playground/src/main/kotlin/team/duckie/quackquack/playground/realworld/TextFieldPlayground.kt
  ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/textfield.kt
Labels: UI

#96 Refactor/fix new line argument
  lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/ComposeIssueRegistry.kt
  lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/NewLineArgumentDetector.kt
  lint-compose/src/test/kotlin/team/duckie/quackquack/lint/compose/NewLineArgumentTest.kt
  ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tab.kt
  ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tag.kt
Labels: lint, deploy, dokka, test

#101 프로젝트 문서 개선
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  quackuser-secrets.tar
Labels: enhancement

#103 Fix the problem that CI failing in external PR
  .github/workflows/android-cd.yml
  .github/workflows/android-ci.yml
  .github/workflows/dokka-deploy.yml
Labels: enhancement

#105 refactor: QuackTextField code cleanup
  .idea/dictionaries/jisungbin.xml
  detekt-config.yml
  ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/textfield.kt
Labels: deploy, dokka

#107 QuackTextField 일부 개선
  playground/src/main/kotlin/team/duckie/quackquack/playground/MainActivity.kt
  playground/src/main/kotlin/team/duckie/quackquack/playground/realworld/TextFieldPlayground.kt
  ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/textfield.kt
  ui-components/src/test/kotlin/team/duckie/quackquack/ui/QuackTextField.kt
Labels: UI, deploy, dokka, test

#109 QuackToggle 구현
  playground/src/main/AndroidManifest.xml
  playground/src/main/kotlin/team/duckie/quackquack/playground/MainActivity.kt
  playground/src/main/kotlin/team/duckie/quackquack/playground/base/common.kt
  playground/src/main/kotlin/team/duckie/quackquack/playground/realworld/TogglePlayground.kt
  ui-components/src/main/kotlin/team/duckie/quackquack/ui/color/QuackColor.kt
  ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/image.kt
  ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/toggle.kt
  ui-components/src/main/kotlin/team/duckie/quackquack/ui/icon/QuackIcon.kt
  ui-components/src/main/res/drawable/ic_bookmark_24_filled.xml
  ui-components/src/main/res/drawable/ic_comment_heart.xml
  ui-components/src/main/res/drawable/ic_comment_heart_filled.xml
  ui-components/src/main/res/drawable/ic_heart_24_white.xml
  ui-components/src/main/res/drawable/ic_heart_filled_24.xml
  ui-components/src/test/kotlin/team/duckie/quackquack/ui/QuackToggle.kt
  ui-components/src/test/kotlin/team/duckie/quackquack/ui/util/paparazzi.kt
Labels: UI, deploy, dokka

#112 migrate to vanniktech
  build-logic/build.gradle.kts
  build-logic/settings.gradle.kts
  build-logic/src/main/kotlin/AndroidLibraryPlugin.kt
  build-logic/src/main/kotlin/AndroidLintPlugin.kt
  build-logic/src/main/kotlin/AndroidQuackPublishPlugin.kt
  build-logic/src/main/kotlin/team/duckie/quackquack/convention/QuackPublishExtension.kt
  build-logic/src/main/kotlin/team/duckie/quackquack/convention/extensions.kt
  build.gradle.kts
  common/build.gradle.kts
  gradle/libs.versions.toml
  lint-compose-publish/build.gradle.kts
  lint-core-publish/build.gradle.kts
  lint-quack-publish/build.gradle.kts
  quack-publish-bom/build.gradle.kts
  scripts/bom-publish-module.gradle
  scripts/publish-module.gradle
  scripts/publish-root.gradle
  settings.gradle.kts
  ui-components/build.gradle.kts
Labels: enhancement

#115 quack publish code cleanup
  build-logic/src/main/kotlin/AndroidQuackPublishPlugin.kt
  build-logic/src/main/kotlin/team/duckie/quackquack/convention/QuackPublishExtension.kt
  gradle/libs.versions.toml
  lint-compose-publish/build.gradle.kts
  lint-core-publish/build.gradle.kts
  lint-quack-publish/build.gradle.kts
  quack-publish-bom/build.gradle.kts
  ui-components/build.gradle.kts
Labels: enhancement

#119 TrailingComma 버그 수정
  lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/TrailingCommaDetector.kt
  lint-compose/src/test/kotlin/team/duckie/quackquack/lint/compose/TrailingCommaTest.kt
  playground/src/main/kotlin/team/duckie/quackquack/playground/base/common.kt
Labels: lint, deploy

#123 improve readme
  README.md
  assets/codestyle-duckie.svg
  assets/logo-icon.svg
  assets/quackquack-logo.svg
Labels: enhancement, deploy, dokka

#132 QuackTextField 완성
  build-logic/src/main/kotlin/team/duckie/quackquack/convention/ApplicationConstants.kt
  common-lint/src/main/kotlin/team/duckie/quackquack/common/lint/MutableCollectionChecker.kt
  playground/src/main/kotlin/team/duckie/quackquack/playground/MainActivity.kt
  playground/src/main/kotlin/team/duckie/quackquack/playground/base/common.kt
  playground/src/main/kotlin/team/duckie/quackquack/playground/realworld/TextFieldPlayground.kt
  playground/src/main/kotlin/team/duckie/quackquack/playground/theme/theme.kt
  playground/src/main/kotlin/team/duckie/quackquack/playground/util/clickable.kt
  ui-components/src/androidTest/kotlin/team/duckie/quackquack/ui/extension.kt
  ui-components/src/androidTest/kotlin/team/duckie/quackquack/ui/modifier/QuackSizeTest.kt
  ui-components/src/androidTest/kotlin/team/duckie/quackquack/ui/util/assrtion.kt
  ui-components/src/main/kotlin/team/duckie/quackquack/ui/border/QuackBorder.kt
  ui-components/src/main/kotlin/team/duckie/quackquack/ui/color/QuackColor.kt
  ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/button.kt
  ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
  ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/image.kt
  ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/internal/QuackText.kt
  ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/internal/TextFielImpl.kt
  ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/surface.kt
  ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tab.kt
  ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tag.kt
  ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/textfield.kt
  ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/toggle.kt
  ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/typography.kt
  ui-components/src/main/kotlin/team/duckie/quackquack/ui/modifier/clickable.kt
  ui-components/src/main/kotlin/team/duckie/quackquack/ui/textstyle/QuackTextStyle.kt
  ui-components/src/main/kotlin/team/duckie/quackquack/ui/util/constraints.kt
  ui-components/src/main/kotlin/team/duckie/quackquack/ui/util/detekt.kt
  ui-components/src/main/kotlin/team/duckie/quackquack/ui/util/layout.kt
  ui-components/src/main/kotlin/team/duckie/quackquack/ui/util/optin.kt
  ui-components/src/test/kotlin/team/duckie/quackquack/ui/QuackButton.kt
  ui-components/src/test/kotlin/team/duckie/quackquack/ui/QuackFab.kt
  ui-components/src/test/kotlin/team/duckie/quackquack/ui/QuackTab.kt
  ui-components/src/test/kotlin/team/duckie/quackquack/ui/QuackTextField.kt
  ui-components/src/test/kotlin/team/duckie/quackquack/ui/QuackToggle.kt
  ui-components/src/test/kotlin/team/duckie/quackquack/ui/provider/DecorationContentProvider.kt
  ui-components/src/test/kotlin/team/duckie/quackquack/ui/provider/QuackIconProvider.kt
  ui-components/src/test/kotlin/team/duckie/quackquack/ui/rule/AnimationTestRule.kt
  ui-components/src/test/kotlin/team/duckie/quackquack/ui/util/paparazzi.kt
  ui-components/src/test/kotlin/team/duckie/quackquack/ui/util_test/AssertionTest.kt
  ui-components/src/test/kotlin/team/duckie/quackquack/ui/util_test/README.md
  ui-components/src/test/kotlin/team/duckie/quackquack/ui/wrapper/NamedValue.kt
Labels: UI, deploy, dokka, test, release

#142 QuackTab 모두 완성
  .idea/codeStyles/Project.xml
  .idea/copyright/MIT.xml
  .idea/copyright/profiles_settings.xml
  .idea/dictionaries/jisungbin.xml
  .idea/vcs.xml
  assets/logo-icon.svg
  assets/quackquack-banner.svg
  build-logic/src/main/kotlin/AndroidApplicationComposePlugin.kt
  build-logic/src/main/kotlin/AndroidApplicationPlugin.kt
  build-logic/src/main/kotlin/AndroidBenchmarkPlugin.kt
  build-logic/src/main/kotlin/AndroidLibraryComposePlugin.kt
  build-logic/src/main/kotlin/AndroidLibraryComposeUiTestPlugin.kt
  build-logic/src/main/kotlin/AndroidLibraryPlugin.kt
  build-logic/src/main/kotlin/AndroidLintPlugin.kt
  build-logic/src/main/kotlin/AndroidQuackPublishPlugin.kt
  build-logic/src/main/kotlin/JvmKoverPlugin.kt
  build-logic/src/main/kotlin/team/duckie/quackquack/convention/ApplicationConstants.kt
  build-logic/src/main/kotlin/team/duckie/quackquack/convention/application.kt
  build-logic/src/main/kotlin/team/duckie/quackquack/convention/extensions.kt
  gradle/libs.versions.toml
  playground/src/main/kotlin/team/duckie/quackquack/playground/realworld/TabPlayground.kt
  playground/src/main/kotlin/team/duckie/quackquack/playground/realworld/TextFieldPlayground.kt
  ui-components/src/androidTest/kotlin/team/duckie/quackquack/ui/modifier/QuackSizeTest.kt
  ui-components/src/androidTest/kotlin/team/duckie/quackquack/ui/util/assrtion.kt
  ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/button.kt
  ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/image.kt
  ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/internal/TextFieldImpl.kt
  ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tab.kt
  ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/textfield.kt
  ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/toggle.kt
  ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/typography.kt
  ui-components/src/main/kotlin/team/duckie/quackquack/ui/modifier/draw.kt
  ui-components/src/main/kotlin/team/duckie/quackquack/ui/util/layout.kt
  ui-components/src/test/kotlin/team/duckie/quackquack/ui/QuackButton.kt
  ui-components/src/test/kotlin/team/duckie/quackquack/ui/QuackFab.kt
  ui-components/src/test/kotlin/team/duckie/quackquack/ui/QuackTab.kt
  ui-components/src/test/kotlin/team/duckie/quackquack/ui/QuackTextField.kt
  ui-components/src/test/kotlin/team/duckie/quackquack/ui/QuackToggle.kt
  ui-components/src/test/kotlin/team/duckie/quackquack/ui/rule/AnimationTestRule.kt
  ui-components/src/test/kotlin/team/duckie/quackquack/ui/util/paparazzi.kt
  ui-components/src/test/kotlin/team/duckie/quackquack/ui/util_test/AssertionTest.kt
  ui-components/src/test/kotlin/team/duckie/quackquack/ui/util_test/RunIfTest.kt
Labels: UI, deploy, dokka, release

#158 baseline profiles 추가
  benchmark-ui-components-app/src/main/baseline-prof.txt
  benchmark-ui-components-app/src/main/kotlin/team/duckie/quackquack/ui/benchmark/app/MainActivity.kt
  benchmark-ui-components-app/src/main/kotlin/team/duckie/quackquack/ui/benchmark/app/benchmark.kt
  benchmark-ui-components/src/main/AndroidManifest.xml
  build-logic/src/main/kotlin/AndroidLibraryPlugin.kt
  build.gradle.kts
  gradle/libs.versions.toml
  playground/build.gradle.kts
  playground/src/main/kotlin/team/duckie/quackquack/playground/benchmark.kt
  ui-components/api/ui-components.api
  ui-components/build.gradle.kts
  ui-components/src/main/baseline-prof.txt
Labels: enhancement
